### PR TITLE
Fix client version and add user agent platform info

### LINKED ISSUE #60: Set SDK version to the current release version
Actually, the client claim's that the version is "1.0.0", but current release is 0.2.3
We should sync version to correctly send headers to API requests

cf https://github.com/shoppingflux/php-sdk/blob/master/src/Client/Client.php#L10

### PR DESCRIPTION
**Pull request by ddattee**
### Link to the issue
This resolves #60 #61 

### Reason for this PR
The version returned by the client is not the one tagged in the repository. 
We needed to add some informations on the platform using the SDK to help integration and debug.

### What does the PR do
Sync the version with the repo.
Allow to add platform information to SDK user agent.

### How to test
On the client when calling `Client::VERSION` the version returned should be 0.2.4.
When setting `userAgentDetails` informations on `ClientOptions` all call made by the SDK should contain the platform used and its version

### CODE REVIEW

**Comment by ddattee** [comment]
I'm gonna add the solution for #61 and fix ut in this PR

File: src/Client/ClientOptions.php [hunk 1]
```diff
@@ -159,4 +159,19 @@ public function addHeaders(array $headers)
...
+     * Add platform information to sdk user agent
+     *
+     * @param string $plateform
+     * @param string $version
+     *
+     * @return ClientOptions
+     */
+    public function setUserAgentDetails($plateform, $version)
+    {
+        $this->headers['User-Agent'] .= " ($plateform;$version)";
```
Comment (ronan-gloo) [inline src/Client/ClientOptions.php]: This will not supports updates (calling the method more than once)
